#!/bin/bash

#getting linux update
apt-get update
#installing design tools
apt-get install figlet toilet
cd
cd Downloads

#install go language
wget https://go.dev/dl/go1.18.3.linux-amd64.tar.gz
tar -C /usr/local/ -xzf go1.18.3.linux-amd64.tar.gz

#setting go path environmental variable
export GOPATH=/usr/local
export GOROOT=/usr/local/go
PATH=$PATH:$GOROOT/bin:$GOPATH/bin
echo 'export GOPATH=/usr/local' >> ~/.zshrc
echo 'export GOROOT=/usr/local/go' >> ~/.zshrc
echo 'PATH=$PATH:$GOROOT/bin:$GOPATH/bin' >> ~/.zshrc
figlet go installation completed

echo "run: source ~/.zshrc"



















